name: "Pack WebExtension"
description: "Packs extension dir using chrome-extension-cli"


runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      shell: bash
      run: npm install

    
    - name: List files in build directory
      run: |
        echo "Debug: Listing files in build directory"
        ls -la ${{ env.BUILD_DIR }}
      shell: bash

    - name: Validate manifest.json of the extension
      uses: cardinalby/schema-validator-action@v1
      with:
        file: ${{ env.EXTENSION_DIR }}manifest.json
        schema: 'https://json.schemastore.org/webextension.json'
