name: "Build, test and pack WebExtension"
description: "Builds, tests, and packs extension dir using chrome-extension-cli"

inputs:
  doNotPackZip:
    description: 'Set `true` to omit pack step'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      shell: bash
      run: npm install

    - name: Build extension
      shell: bash
      run: npm run build

    - name: Pack extension
      if: inputs.doNotPackZip != 'true'
      shell: bash
      run: npm run pack
    
    - name: Debug: List files
        run: ls -R

    - name: Validate manifest.json of the extension
      uses: cardinalby/schema-validator-action@v1
      with:
        file: ${{ env.EXTENSION_DIR }}manifest.json
        schema: 'https://json.schemastore.org/webextension.json'
